dist: xenial
sudo: required
language: node_js
node_js:
  - "10"
script:
    - npm i -g electron
    - npm i -g electron-builder
    - npm install
install:
    - sudo apt-get update
    - sudo apt-get install --no-install-recommends -y libopenjp2-tools
    - sudo apt-get install --no-install-recommends -y rpm
    - sudo apt-get install --no-install-recommends -y snapcraft
after_success:
    - npm run build:linux
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file:
    - "dist/*.deb"
    - "dist/*.rpm"
    - "dist/*.AppImage"
    - "dist/*.snap"
  skip_cleanup: true
  on:
    tags: true

deploy:
  provider: snap
  snap: dist/*.snap
  channel: edge
  skip_cleanup: true
  on:
    tags: true